### ISSUE TITLE
Does Docker works?

### ISSUE THREAD

**Issue by eliasjnior** [mikigal/ryzen-hackintosh#11]
Hey! I'm looking to install OSX on my new desktop. But one thing I really need is Docker running. No matter if doesn't have the best performance, but I need it to run.

Did you try to install Docker? You said virtualization is partially working. 

Regards!

**Comment by mikigal** [comment]
Hi,
as Dortania troubleshooting guide says 
> Docker toolbox is the only solution as it's based off of VirtualBox, many features are unavailable with this version

I'm not advanced with Docker, so I'm not sure about differences between Docker and Docker Toolbox
Look at this: https://docs.docker.com/docker-for-mac/docker-toolbox/
