### ISSUE TITLE
Black screen on boot install

### ISSUE THREAD

**Issue by xellDart** [mikigal/ryzen-hackintosh#12]
Hi, i use your efi, follow your instructions, but when i boot for install, i select, Install mac, later apple mac logo appears, when the progress bar is complete i get black screen

Can you help me whit this?

My hardware is:
MOBO: Gigabyte AB 350 Gaming 3-CF
RX 5700XT
Crucial SSD 1 TB

**Comment by mikigal** [comment]
Add `agdpmod=pikera` to boot-args in config.plist. This parameter is required for 5700XT

**Comment by y1024** [comment]
add to where ?
thanks

**Comment by mikigal** [comment]
You have to add it to boot parameters. Open config in text editor/ProperTree/another tool and search for "boot-args". Then add agdpmod=pikera to arguments
