### ISSUE TITLE
Boot crashes right after OpenCore Bootscreen

### ISSUE THREAD

**Issue by flo071** [mikigal/ryzen-hackintosh#14]
So, i followed the guide, then wanted to boot it up, cameto the OpenCore boot menu, clicked on the drive i want to boot from, then the apple logo showed, after this for a short moment, the loading bar under the apple logo was visible, then the PC rebooted.

My hardware:
CPU: AMD Ryzen 7 1700
MOBO: ASRock AB350M Pro4
RAM: 24GB
GPU: Radeon RX 590 Series

**Comment by mikigal** [comment]
Run it in verbose Mode and send logs. I can't help without that

**Comment by flo071** [comment]
Is this what you need? 
[opencore-2020-11-13-103051.txt](https://github.com/mikigal/ryzen-hackintosh/files/5536230/opencore-2020-11-13-103051.txt)

**Comment by mikigal** [comment]
That's not full log. Please send screen of kernel panic

**Comment by flo071** [comment]
So, i finally caught it. Here it is: ![IMG_20201116_155512](https://user-images.githubusercontent.com/17823651/99267731-9c3b5580-2824-11eb-8836-2d8cf1b1f4c8.jpg)

**Comment by Maxung** [comment]
So I'm no expert, but I it clearly states it's an ACPI error (related to sleep PRW?). I would try disabling the ACPI sleep fixes in the config and try again

**Comment by mikigal** [comment]
@flo071 @Maxung Can you send me your DSDT? It looks i broke something with _PRW in my SSDT. Temporary disable SSDT-SLEEP in config.plist

**Comment by mikigal** [comment]
Please try SSDT-SLEEP from latest commit, let me know does it work

**Comment by flo071** [comment]
Will do that and report back. Thank you gusy for the help.

**Comment by flo071** [comment]
Came to this now: 
![IMG_20201117_094711](https://user-images.githubusercontent.com/17823651/99367186-ee7a8600-28b9-11eb-815f-2eb8157fd707.jpg)
I already tried the methods from the troubleshooting section to fix this, but seems like there is no change..

**Comment by Maxung** [comment]
I would try to check BIOS settings again (like CSM is off, etc.) and try with a USB 2.0 port. Also NVRAM reset might help, but other than that I don't know

**Comment by flo071** [comment]
Thank you, will try resetting NVRAM, did the rest. I only use the 2.0 ports for hackintosh..

**Comment by Maxung** [comment]
Ok, then you might want to try the configs from this repository (it's Catalina, so I don't know if Big Sur works) but he uses the same mainboard as you. https://github.com/alkalim/ryzen-catalina

**Comment by flo071** [comment]
Well, I now tried all my USB ports, same thing on every port.. Resetting NVRAM does nothing too, it still freezed at ```HID: Legacy shim 2```

**Comment by mikigal** [comment]
Does it boot without SSDT-SLEEP?

**Comment by flo071** [comment]
it does not boot, but it gets stuck at ```HID: Legacy shim 2```, but it does not crash anymore.

**Comment by mikigal** [comment]
https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html#stuck-on-rtc-pci-configuration-begins-previous-shutdown-hpet-hid-legacy

Try this

**Comment by flo071** [comment]
So, i now started all over again, now it went further. Now it is stuck at: ```apfs_module_stop:2495: unload: com.apple.filesystems.apfs, v1677.50.1, 2020/10/30 (remaining mem allocated: 0)```

**Comment by Maxung** [comment]
I'm wondering, did you try the Catalina repository I send? I think it's only a good idea to try a prebuilt config (from this repository), if you have the same mainboard (or very similar)
(Also this time you went past the graphic initialisation and have lots of Ryzen related patching? errors)

**Comment by flo071** [comment]
Yes, i tried the catalina repo, did not work. Now i have rebooted once, it changes the lines where ryzen was mentioned to iMac-Pro.local..

i have reset the NVRAM one more time now but its still the same issue..

**Comment by Maxung** [comment]
If you want you can try the attached, slightly modified, config from this repository. Otherwise if you are sure you setup the macOS installer correctly, I'm out of ideas.
[ryzen-hackintosh-master.zip](https://github.com/mikigal/ryzen-hackintosh/files/5566706/ryzen-hackintosh-master.zip)

**Comment by flo071** [comment]
I will try that, thank you!

If this does not work i will try other methods of setting up the USB..

**Comment by flo071** [comment]
and again, here we are with ```apfs_module_stop:2495: unload: com.apple.filesystems.apfs, v1677.50.1, 2020/10/30 (remaining mem allocated: 0)```

**Comment by flo071** [comment]
Well, I just left it while I was eating, now an hour later it went further, looks like I am in this stage: https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html#stuck-at-forcing-cs-runtime-for-entitlement-in-big-sur

There it states that it may take some time, but is it normal that it takes that long?

**Comment by mikigal** [comment]
Are you get this while booting installer or after booting from OS partition after preinstall? Sealing volume is later, after first stage of installation.

**Comment by flo071** [comment]
I am booting the installer USB right now..
I can send another picture of where it is now, if that helps..

**Comment by flo071** [comment]
So, i tried setting it up freshly, set up the USB with the linux method 2, still the same issue, stuck here: ```apfs_module_stop:2495: unload: com.apple.filesystems.apfs, v1677.50.1, 2020/10/30 (remaining mem allocated: 0)```

**Comment by flo071** [comment]
I got the issue fixed, it was a GPU problem, as XFX Graphics card is not supported by macOS (as is seems?). What i did is flashing another vbios from PowerColor. It booted up now. Installing now. Thank you both for your help guys!!
