### ISSUE TITLE
Reboots on boot

### ISSUE THREAD

**Issue by vleeuwenmenno** [mikigal/ryzen-hackintosh#15]
Hey I am trying your thing on my PC.
I have a 3900X with a RX 5700 XT
 MPG X570 GAMING PLUS motherboard.

I setup a USB from my MacBook Pro 2018 with BigSur
But it boots to the menu and I select install bigsur, then it shows my pc has a problem so I must press a key or wait a few seconds to continue.

After that it shows the apple logo and it reboots in 30 seconds to Windows which I still have on my second NVMe
EDIT: Photo of the message
![image](https://user-images.githubusercontent.com/46482143/99842816-cf594e00-2b70-11eb-842a-794d080ba235.png)

**Comment by mikigal** [comment]
Hi,
It looks like kernel panic on early boot stage. Please add "-v debug=0x100" to boot-args in config.plist. It will show logs while booting, then send picture of kernel panic

**Comment by vleeuwenmenno** [comment]
I'm running a 
- Ryzen 9 3900X
- 32GB of 3733Mhz DDR4
- RX 5700 XT
- MSI MPG x570 Gaming Plus WIFI
- NVMe 256GB 970 Evo

Boot args = -v debug=0x100 npci=0x2000 alcid=11 agdpmod=pikera
MacOS Big Sur 11.0.1

![image](https://user-images.githubusercontent.com/46482143/99850376-8d82d480-2b7d-11eb-9c21-26df446568ee.png)

**Comment by vleeuwenmenno** [comment]
I managed to make it bootable by updating all the kexts to the latest. Now I only have the problem that I have no mouse and keyboard.

**Comment by mikigal** [comment]
All kexts in this repository are update to it's latest release version. Please read this: https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html#stuck-on-rtc-pci-configuration-begins-previous-shutdown-hpet-hid-legacy

Do you have enabled SSDT-SLEEP in config.plist?

**Comment by vleeuwenmenno** [comment]
Hi, I managed to make it boot and work. I just had to disconnect all my monitor HUBs and reconnect the USB kb and mouse and it all started working.

**Comment by mikigal** [comment]
In most cases USB should work OOTB.
