### ISSUE TITLE
everything works but chrome freeze system ui

### ISSUE THREAD

**Issue by pynixwang** [mikigal/ryzen-hackintosh#16]
system ui freeze when open chrome or electron app.

can move mouse

**Comment by mikigal** [comment]
If you can move mouse it's not kernel panic, I never seen similar issue. 

Try to disable (or enable if it is enabled now) hardware acceleration in Chrome. Post your specs too

**Comment by pynixwang** [comment]
@mikigal wrong product model, MacPro6,1 works.
