### ISSUE TITLE
Would it work on a 3900x/5900x?

### ISSUE THREAD

**Issue by cyrusauyeungc** [mikigal/ryzen-hackintosh#18]
This build looks marvellous! And I’m trying to source the similar hardware. 
just asking if you’d know the CPU upgrade would work?and do we need special Broadcom WiFi card to enable airdrop/handoff? Thanks.

**Comment by mikigal** [comment]
Ryzen 3gen should work too. For AirDrop/Handoff you need native supported card, check this buying guide: https://dortania.github.io/Wireless-Buyers-Guide/
