### ISSUE TITLE
I can get into the setup it's always have an prohibited sign especially when I restart

### ISSUE THREAD

**Issue by Quzard** [mikigal/ryzen-hackintosh#2]

**Comment by Quzard** [comment]
how can i solver it？

**Comment by mikigal** [comment]
Boot into verbose mode, and send your logs, possibly kernel panic

**Comment by Quzard** [comment]
Error allocating 0x5de3  pages at 0x00000000072e000 alloc type 2

Couldn't allocate runtime area

**Comment by Quzard** [comment]
In addition to memory, graphics and SSD, my PC specification is the same as yours

Component | Model
-- | --
CPU | AMD Ryzen 7 1700 @ 3.8GHz
Motherboard | ASUS B350 Plus
RAM |  TEAMGROUP T-Force Vulcan DDR4 8 GB  2400MHz (PC4-19200) CL16 
Audio Chipset | ALC-887
GPU | Sapphire RX 470 4G
OS Disk (NVMe) | LITEON T10 250GB

**Comment by mikigal** [comment]
Sometimes I have similar problem, try reboot it few times, it works for me. You can try to port config to OpenCore, it should finally fix this issue.

**Comment by Quzard** [comment]
I reboot too.
Thanks for your help

**Comment by QinghuiWang** [comment]
i have the same  problem,when i boot my mac os,It will  random report a error that loading kernel cache(0x9)。
Do you still have this problem？

**Comment by Quzard** [comment]
sometimes

**Comment by mikigal** [comment]
Port EFI from Clover to OpenCore should fix this issue, but I haven't any experience with OC so I stay on Clover. If you can port it, create pull request please :) 

Currently, you must reboot PC few times If u get this error

**Comment by mikigal** [comment]
Problem fixed, I ported EFI to OpenCore. Try with OC version

**Comment by QinghuiWang** [comment]
@mikigal  
Think you.
I solved this problem by modifying the slide value. See more ：https://blog.daliansky.net/Slide-value-acquisition-and-calculation.html
