### ISSUE TITLE
When I select MacOS in the boot loader, an error appears and the PC restarts

### ISSUE THREAD

**Issue by azrhodo** [mikigal/ryzen-hackintosh#22]
hello, when I select MacOS in the boot loader (with verbose mode enabled) it gives me an error then restarts a few minutes later. Here is my hardware
| Component   | Model                                |
|-------------|--------------------------------------|
| CPU         | AMD Ryzen 5 1600 6-cores             |
| MotherBoard | Asus PRIME-B350 PLUS                 |
| RAM         | 2xG.Skill Aegis 8 GB (1 x 8 GB) DDR4 |
| GPU         | Sapphire AMD RX460 4GB               |

![6D1122C8-5CAE-441A-80A9-9365FD8E6306](https://user-images.githubusercontent.com/83612171/116933502-ed6cc380-ac63-11eb-8e9b-6717932f1efc.jpeg)

![175615E0-2724-479D-A0C7-16DF55F979EE](https://user-images.githubusercontent.com/83612171/116933551-fb224900-ac63-11eb-8686-f41e0bdcefb9.jpeg)

**Comment by mikigal** [comment]
Looks like broken ACPI or problem with SMCAMDProcessor/AMDRyzenCPUPowerManagement.
Remove both kexts (remember to remove it from config), update your BIOS to latest version and try again

**Comment by azrhodo** [comment]
I simply updated the BIOS and it worked! Now I just have to know if the installation will work. Thanks!
