### ISSUE TITLE
When macOS is selected in the boot loader, an error comes up and then restarts

### ISSUE THREAD

**Issue by devins-07** [mikigal/ryzen-hackintosh#25]
hi, I had a similar error to this thread, [https://github.com/mikigal/ryzen-hackintosh/issues/22]
I looked at the comments for the solution and I updated my bios and removed the SMCAMDProcessor/AMDRyzenCPUPowerManagement Kexts, after that, a different error came up while loading. 
after I select macOS from the boot loader it comes up with this error,

![IMG_7405](https://user-images.githubusercontent.com/80927794/123183675-0e7db380-d460-11eb-80a0-ff84389352aa.JPG)

then after about a minute the code keeps going and it comes up with this error, 

![IMG_7418](https://user-images.githubusercontent.com/80927794/123183730-27866480-d460-11eb-818d-1b593b993f3f.JPG)

and then one minute later, the pc restarts, I will list my specs below and would appreciate any help considering that I have followed around 5 tutorials none of which I was able to install macOS with

| **Component**    | **Model**            |
| ---------------- | -------------------- |
| CPU              | [AMD Ryzen 5 3600 6-Cores]           |
| Motherboard      | [MSI Tomahawk B450 MAX]   |
| GPU              | [Nvidia GT710 (I know its a bad gpu)]           |
| RAM    | [2x TFORCE 8gb DDR4 and 2x Zadak 8gb DDR4 ] |

**Comment by mikigal** [comment]
Which macOS version are you trying to boot?

**Comment by devins-07** [comment]
its Macos Bigsur

**Comment by mikigal** [comment]
Redirected in DMs to AMD-OSX forum, looks like hardware specific issue
