### ISSUE TITLE
Gigabyte X570 Aorus Elite

### ISSUE THREAD

**Issue by xellDart** [mikigal/ryzen-hackintosh#26]
Hi, can I use this with this PC:

CPU | AMD Ryzen 9 5900X
-- | -- 
Mainboard | Gigabyte X570 Aorus Elite
Graphics | AMD Radeon RX 5700 XT 8GB GDDR6 RAW
NVMe | WD Black SN750 500GB

or what patches I need to use?

**Comment by mikigal** [comment]
Just read README in repository instead of creating issue and asking...
Yes, you can.
