### ISSUE TITLE
how to disable mouse at bootload?

### ISSUE THREAD

**Issue by shaw830** [mikigal/ryzen-hackintosh#27]
| **Component**    | **Model**            |
| ---------------- | -------------------- |
| CPU              | ryzen 1700]           |
| Motherboard      | [ausa b350]   |
| GPU              | [rx580]           |
| Audio Chipset    | [Your audio chipset] |
| Ethernet         | [Your Ethernet card] |
| WiFi & Bluetooth | [Your WiFi card]     |

thank your EFI bootload, it was good work on my hackintosh. a little problem when i update opencore 0.7.1: how to disable mouse at bootload?

**Comment by mikigal** [comment]
You have to set `PickerAttributes` to `1`. Cursor was enabled in [this commit](https://github.com/mikigal/ryzen-hackintosh/commit/c446f9ffc1b70328d11e8abcd6068244310bbd4a) so you can change diff if you don't know how to disable it.
