### ISSUE TITLE
Reset NVRAM

### ISSUE THREAD

**Issue by Titeiiko** [mikigal/ryzen-hackintosh#28]
| **Component**    | **Model**            |
| ---------------- | -------------------- |
| CPU              | AMD A4 (Quad Core, 1.8GHZ)           |
| Motherboard      | Not Sure   |
| GPU              | Radeon Graphics R5           |
| Audio Chipset    | [Your audio chipset] |
| Ethernet         | [Your Ethernet card] |
| WiFi & Bluetooth | [Your WiFi card]     | These 3 idk

I downloaded the EFI (i didn't adjust it) and just slapped it onto my USB drive and it worked...kinda. It brings me to a "Reset NVRAM" area and it just doesn't do anything else. If I press the 'up' button then it restarts laptop.

**Comment by Titeiiko** [comment]
sry for not including the audio, ethernet, wifi, etc. I just didn't where / what it was.

**Comment by mikigal** [comment]
Support for 16h CPU (e. g. A series) are not covered in this repository.

You have inky reset nvram because you don't have installer on USB - but EFI from this repository won't work for your 16h CPU
