### ISSUE TITLE
Low CPU performance

### ISSUE THREAD

**Issue by Tyrone2333** [mikigal/ryzen-hackintosh#3]
2600 + 5500xt

Open webstorm freeze, CPU idle is always greater than 85%, memory frequency shows 1200, is this the case for all amd CPUs?

![_AA540F43-AE02-1F64-12DB-3A26AAF83A2F_.png](https://i.loli.net/2020/03/10/p2UKA7RFo31zCle.png)

![OT_MRGRIA_Z7`QZBCT_SSJ9.png](https://i.loli.net/2020/03/10/BDuvkKHwjzOUQo6.png)

**Comment by mikigal** [comment]
Your results in Geekbenchs are normal for that CPU. Check this https://browser.geekbench.com/v5/cpu/search?utf8=✓&q=ryzen+5+2600

I haven't any problems with performance, Webstorm and other JetBrains software work great
Which process use CPU in idle?

**Comment by Tyrone2333** [comment]
> @Tyrone2333
> 
> Your results in Geekbenchs are normal for that CPU. Check this [https://browser.geekbench.com/v5/cpu/search?utf8=✓&q=ryzen+5+2600](https://browser.geekbench.com/v5/cpu/search?utf8=%E2%9C%93&q=ryzen+5+2600)
> 
> I haven't any problems with performance, Webstorm and other JetBrains software work great
> Which process use CPU in idle?

It took me 4 minutes to build a simple vue application, do you know why? My cpu is always idle, can you help me?
![DB3E45BAC55BC4D599F7FD79DB577586.png](https://i.loli.net/2020/03/10/SeDHVkNyKZIf3jC.png)

**Comment by mikigal** [comment]
I don't know why it's so slow, it's not every AMD build problem.
Ask on AMD-OSX Discord, maybe someone can help you
https://discord.gg/EfCYAJW

**Comment by Tyrone2333** [comment]
I reinstalled the system to SSD, and now everything is normal. Maybe it's because the HDD drags down the CPU,I'm not sure
