### ISSUE TITLE
Cant find monterey link

### ISSUE THREAD

**Issue by devins-07** [mikigal/ryzen-hackintosh#30]
I cant find the link for monterey

https://imgur.com/gallery/bniozMl

**Comment by mikigal** [comment]
Hi,
macrecovery.py does not support Monterey for now, or Dortania guide is not updated.
I think easiest way to get Monterey from Windows is installing Big Sur, then updating to Monterey via beta profile, or get it's installer with [gibMacOS](https://github.com/corpnewt/gibMacOS) and make clean install.
