### ISSUE TITLE
Use HfsPlus instead of OpenHfs

### ISSUE THREAD

**Issue by kamalhm** [mikigal/ryzen-hackintosh#31]
OpenHfsPlus is slower than HfsPlus and no longer recommended in dortania.

https://dortania.github.io/OpenCore-Install-Guide/ktext.html#universal

**Comment by mikigal** [comment]
Hi, thanks for your report. 
I verified this informations in OpenCore documentation, it says OpenHfsPlus is about 3x times slower.

Closed in https://github.com/mikigal/ryzen-hackintosh/commit/3bec0671a225245e3700fa96ec31b136c7a9dbac
