### ISSUE TITLE
Use USBToolBox kext for easier USB port mapping

### ISSUE THREAD

**Issue by kamalhm** [mikigal/ryzen-hackintosh#32]
Contrary to what is said on dortania, we can use https://github.com/USBToolBox/kext and generate the usb mapping automatically using https://github.com/USBToolBox/tool, this step should be added on the preparation because the tool need to be run on windows

**Comment by mikigal** [comment]
Hi, thanks for your report.
In README there was already information about mapping with USBToolBox, but I moved it to `Configuration` section as you proposed. Also added USBToolBox.kext by default.

Closed in https://github.com/mikigal/ryzen-hackintosh/commit/5cdacb70606bf2b218980de8649a2f4f7b8f2b2e

**Comment by kamalhm** [comment]
Thanks a lot! Quick question, I noticed there's an updated additional step on post install, applying ryzen patch. Is this supposed to fix sleep issues with AMD hackintosh, even after properly mapping USB?

**Comment by mikigal** [comment]
Applying these PM properties is recommended for all hackintoshes, it mainly disables mechanisms that can automatically wake up PC.

Disables autopoweroff: This is a form of hibernation
Disables powernap: Used to periodically wake the machine for network, and updates(but not the display)
Disables standby: Used as a time period between sleep and going into hibernation
Disables wake from iPhone/Watch: Specifically when your iPhone or Apple Watch come near, the machine will wake
Disables TCP Keep Alive mechanism to prevent wake ups every 2 hours

Source: https://dortania.github.io/OpenCore-Post-Install/universal/sleep.html#preparations
