### ISSUE TITLE
Stuck at #[EB|LOG:EXITBS:START]

### ISSUE THREAD

**Issue by shrikant2002** [mikigal/ryzen-hackintosh#33]
I am Stuck here after boot selection #[EB|LOG:EXITBS:START]

I am using OC debug 0.7.3
hardware 
Asus B450m-a
Ryzen 5 2600
RX 460
I have attached my EFI
[EFI.zip](https://github.com/mikigal/ryzen-hackintosh/files/7169127/EFI.zip)

**Comment by mikigal** [comment]
Hi,
you didn't modify kernel patches for your CPU, it's described [here](https://github.com/mikigal/ryzen-hackintosh#installation).

Please read whole README before creating issues.

**Comment by shrikant2002** [comment]
I tried substituting my core count 06 in replace value as well here is efi but still the same issue 
[EFI.zip](https://github.com/mikigal/ryzen-hackintosh/files/7170368/EFI.zip)

**Comment by mikigal** [comment]
Kernel patches look good.
Try updating your BIOS to latest version. If it still does not work then, probably something under Booter -> Quirks is wrong. Check [this guide](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html#stuck-on-eb-log-exitbs-start)
For future question please join [AMD-OSX Discord](https://discord.gg/EfCYAJW)
