### ISSUE TITLE
Sudden Restarts & Kernel Panic

### ISSUE THREAD

**Issue by shrikant2002** [mikigal/ryzen-hackintosh#34]
| **Component**    | **Model**            |
| ---------------- | -------------------- |
| CPU              | [Ryzen 5 2600]           |
| Motherboard      | [Asus B450m-a]   |
| GPU              | [rx460]           |

**Link to your EFI**: [attached]

After using my hackintosh for sometime. I am getting the following kernel panic and my hackintosh restarts 

panic(cpu 0 caller 0xffffff8019bc57d6): Kernel trap at 0xffffff801ca24906, type 14=page fault, registers:
CR0: 0x000000008001003b, CR2: 0x0000000120000065, CR3: 0x0000000023f16000, CR4: 0x00000000000406e0
RAX: 0x0000000020000004, RBX: 0x0000000020000004, RCX: 0xffffff801c8f5e94, RDX: 0xffffff9387809900
RSP: 0xffffffa11035bd30, RBP: 0xffffffa11035bdd0, RSI: 0x0000000000000003, RDI: 0xffffff9387809900
R8:  0x0000000000000008, R9:  0x0000000000989680, R10: 0xffffff93836d45c0, R11: 0xffffff86bc09f640
R12: 0xffffffa10ccf26c0, R13: 0x00000000e00002d5, R14: 0x000000000000000d, R15: 0xffffff93880b83c0
RFL: 0x0000000000010206, RIP: 0xffffff801ca24906, CS:  0x0000000000000008, SS:  0x0000000000000000
Fault CR2: 0x0000000120000065, Error code: 0x0000000000000002, Fault CPU: 0x0, PL: 0, VF: 1

Backtrace (CPU 0), Frame : Return Address
0xffffffa11035b750 : 0xffffff8019a8e04d 
0xffffffa11035b7a0 : 0xffffff8019bd4e13 
0xffffffa11035b7e0 : 0xffffff8019bc540a 
0xffffffa11035b830 : 0xffffff8019a32a2f 
0xffffffa11035b850 : 0xffffff8019a8d86d 
0xffffffa11035b970 : 0xffffff8019a8db63 
0xffffffa11035b9e0 : 0xffffff801a29dc0a 
0xffffffa11035ba50 : 0xffffff8019bc57d6 
0xffffffa11035bbd0 : 0xffffff8019bc54bd 
0xffffffa11035bc20 : 0xffffff8019a32a2f 
0xffffffa11035bc40 : 0xffffff801ca24906 
0xffffffa11035bdd0 : 0xffffff801ca2515e 
0xffffffa11035bdf0 : 0xffffff801ca42a03 
0xffffffa11035be20 : 0xffffff801ca32e08 
0xffffffa11035bee0 : 0xffffff801a1ef630 
0xffffffa11035bf30 : 0xffffff801a1edd9e 
0xffffffa11035bf70 : 0xffffff801a1ed386 
0xffffffa11035bfa0 : 0xffffff8019a3213e 
      Kernel Extensions in backtrace:
         com.apple.driver.usb.AppleUSBXHCI(1.2)[6EB13870-F707-33FC-AFF1-4004C0EE817D]@0xffffff801ca20000->0xffffff801ca6dfff
            dependency: com.apple.driver.usb.AppleUSBCommon(1.0)[00F51613-51A3-3973-BF4C-2E87294EF717]@0xffffff801b2a6000->0xffffff801b2a9fff
            dependency: com.apple.iokit.IOACPIFamily(1.4)[6E5C8A04-2B99-3BE0-A928-C069089CCE00]@0xffffff801c044000->0xffffff801c045fff
            dependency: com.apple.iokit.IOUSBHostFamily(1.2)[3FDCC3CF-64A8-3794-A52C-5D8DE43A8265]@0xffffff801c88a000->0xffffff801c918fff

Process name corresponding to current thread: kernel_task
Boot args: unfairgva=1 alcid=1 

Mac OS version:
20G95

Kernel version:
Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64
Kernel UUID: FECBF22B-FBBE-36DE-9664-F12A7DD41D3D
KernelCache slide: 0x0000000019800000
KernelCache base:  0xffffff8019a00000
Kernel slide:      0x0000000019810000
Kernel text base:  0xffffff8019a10000
__HIB  text base: 0xffffff8019900000
System model name: MacPro7,1 (Mac-27AD2F918AE68F61)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 4519633283440
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x0000041c4f22ec87
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x0000001977584290 0x0000000000000000

[EFI.zip](https://github.com/mikigal/ryzen-hackintosh/files/7204979/EFI.zip)

**Comment by mikigal** [comment]
Hi,
it looks like USB issue. Did you make map for your ports?

**Comment by shrikant2002** [comment]
[EFI.zip](https://github.com/mikigal/ryzen-hackintosh/files/7204748/EFI.zip)
Here is the EFI. I did USB Mapping already pls check my efi

**Comment by mikigal** [comment]
Your map kext (`UTBMap.kext`) isn't added to config, you have to add it. Remember that it's only Info.plist kext, so leave `ExecutablePath` empty.

**Comment by shrikant2002** [comment]
I did oc clean snapshot in propertree isn't that enough?

**Comment by shrikant2002** [comment]
![Screenshot 2021-09-21 at 9 58 58 PM](https://user-images.githubusercontent.com/1228193/134211074-aaee55ac-d1f5-49ef-be87-71fceaf6707b.png)
I think it is present and ExecutablePath is empty

**Comment by shrikant2002** [comment]
I think it is present and ExecutablePath is empty already
![Screenshot 2021-09-21 at 10 06 05 PM](https://user-images.githubusercontent.com/1228193/134211193-58fff261-09ca-4b8b-ba5d-564053a5a44d.png)

**Comment by mikigal** [comment]
> I think it is present and ExecutablePath is empty already
> ![Screenshot 2021-09-21 at 10 06 05 PM](https://user-images.githubusercontent.com/1228193/134211193-58fff261-09ca-4b8b-ba5d-564053a5a44d.png)

Looks good. Please Join AMD-OSX Discord server and ask about your issue there. Here's only basic support with booting. I'm not sure about reason of your problem

**Comment by shrikant2002** [comment]
okay thanks for your time great config by the way thanks for that !
