### ISSUE TITLE
Resources

### ISSUE THREAD

**Issue by DemoorBug** [mikigal/ryzen-hackintosh#37]
'Resources/ryzen_patch.sh
Resources/adobe_patch_legacy.sh
Resources/adobe_patch.sh
Do all three of these files have to be executed in the terminal?

I used opencore for the first time and it installed bigsur11.6 perfectly, your project is great!

**Comment by DemoorBug** [comment]
I use abobe's After Effects and Photoshop

**Comment by DemoorBug** [comment]
Okay, thanks

**Comment by DemoorBug** [comment]
Can I ask what problems are solved by the ryzen patch, and is there a link to the author and a description?

**Comment by mikigal** [comment]
Ryzen patch mainly applies MKL patch - it solves crashes in a lot of applications, e. g. voice channel on Discord. Source of this party is old XLNC's Adobe patch.
Additionally it applies some sleep parameters to make sure OS won't randomly wake up. Source of this parameters is Dortania guide.

**Comment by DemoorBug** [comment]
It's really detailed. Thanks again
