### ISSUE TITLE
Support/Hope For Laptop Amd Processors ?

### ISSUE THREAD

**Issue by rohitsangwan01** [mikigal/ryzen-hackintosh#38]
| **Component**    | **Model**            |
| ---------------- | -------------------- |
| CPU         | Ryzen 5 4600H           |

Hey , thats Really great Work , but am searching for a Way to make hackintosh work in Amd Ryzen 5 4600H + 1650ti , but there is no such process for this on Whole internet , or atleast i havent found one yet , is there any hope for this Laptop maybe in future , or maybe any method available Currently
https://www.lenovo.com/in/en/laptops/ideapad/ideapad-gaming-laptops/IdeaPad-Gaming-3-15IHU6/p/88IPG301588

**Comment by mikigal** [comment]
There's no way to get AMD based laptop working. AMD APUs are not supported.
