### ISSUE TITLE
Installation of MacOS crashes

### ISSUE THREAD

**Issue by Jeazyee** [mikigal/ryzen-hackintosh#4]
Hello, your EFI is working fine until it gets to the macOS installation. I removed your Realtek Ethernet kext and changed it to my needed one, also changed this in the config.plist. Beyond that everything is similar. Booting works fine and I can play around the macOS Utilities without any problems and internet is working too. But the installation of macOS crashes after I select my M.2 SSD which I had formatted to APFS in DiskUtility.

Here is the crash report of the installer, hope you can help me fix that issue.
https://justpaste.it/4ux9t

My System:
Mainboard: ASUS Crosshair VII Hero
CPU: AMD Ryzen 1700X
GPU: RTX 2070 super (I know its not supported but I don't care about low performance)
RAM: Night Hawk RGB (2 x 8GB, DDR4-3200)
DISK: 500GB M.2 Samsung 960 EVO NVMe SSD

**Comment by mikigal** [comment]
I'm not sure why it crash while installing, but trust me, that's not only "low performance" on your GPU. You won't have GPU acceleration, so every animation won't work, you will have lot of glitches on screen. You won't use it longer than 10 minutes.

**Comment by mikigal** [comment]
`No compatibility bundle on this version of macOS. Will assume compatible.`
It looks that installer has some problems with hardware, I guess it can be GPU related.
