### ISSUE TITLE
Kepler H264/HEVC decoding support on Big Sur

### ISSUE THREAD

**Issue by djmuted** [mikigal/ryzen-hackintosh#41]
| **Component**    | **Model**            |
| ---------------- | -------------------- |
| CPU              | AMD Ryzen 7 1800X Eight-Core Processor            |
| Motherboard      | QEMU KVM   |
| GPU              | NVIDIA NVS 510 2 GB           |
| Audio Chipset    | External audio USB card |
| Ethernet         | E1000 |
| WiFi & Bluetooth | None     |

I got HW accel for the GPU working out of the box, but VideoProc shows that H264/HEVC is not supported.
Is there any way to get it working?

**Comment by mikigal** [comment]
@djmuted If you get any progress with your issue please let me know
