### ISSUE TITLE
adobe_patch.sh does not run correctly with folder name with spaces 

### ISSUE THREAD

**Issue by Scarle-t** [mikigal/ryzen-hackintosh#42]
I have many adobe apps installed (Photoshop, After Effects just to name a few), and when I ran the script with ``` sh adobe_patch.sh ``` the script output ```No such file or directory.``` error and I have no idea if the script ran successfully or not
Here is the terminal output
![image](https://user-images.githubusercontent.com/41410982/142231917-a71c6d0c-dd9e-4974-8636-9e120f684102.png)
(ps: I have fish installed and I though it was causing problems so I ran the script with zsh again and still no luck)

I have looked into the script but with limited knowledge of shell script I have no idea where to add quotes for the path.

I have also tried copying and pasting the script directly to terminal and it won't run

System Spec:
|Item|Spec|
|---|---|
|OS|macOS Monterey 12.0.1 (21A559)|
|Adobe Software|CC 2022|
|||
| CPU  | AMD Ryzen 5 3600XT |
| RAM  | 32GB  |
| Motherboard  | Asus TUF B450M  |
|Graphics|RX 5700XT|
|Storage macOS Disk | 1TB SATA SSD 
|Storage Attached| M.2 250GB x1, 2TB HDD x3|

**Comment by mikigal** [comment]
Hi,
thanks for very detailed issue.
It looks that https://github.com/mikigal/ryzen-hackintosh/commit/77fbc11aae805e0d09880861623cfe8f0ed28a02 fixed problem, please verify does it work on your machine and let me know
