### ISSUE TITLE
Error in boot 10.15.7. I have modified and tried it many times

### ISSUE THREAD

**Issue by kristinaking** [mikigal/ryzen-hackintosh#43]

**Comment by mikigal** [comment]
Please add informations from issue template and logs.

**Comment by kristinaking** [comment]
| **Component**    | **Model**            |
| ---------------- | -------------------- |
| CPU              | [2600x]           |
| Motherboard      | [msi b450m mortar]   |
| GPU              | [vega64]           |
| Audio Chipset    | [alc892] |
| Ethernet         | [rtl81111] |
| WiFi & Bluetooth | [fenvi t919]     |
![WechatIMG1](https://user-images.githubusercontent.com/57547429/142408030-420c79b3-bd66-4f85-8957-eef98dcb063c.jpeg)


The extracted log is blank and can only be screenshot

**Comment by mikigal** [comment]
Try using older version of Lilu and other kexts if needed (they may require latest Lilu) as you are using old macOS

**Comment by kristinaking** [comment]
OK, I'll try

**Comment by mikigal** [comment]
Did it resolve issue?
