### ISSUE TITLE
kernel_task mouse stuck

### ISSUE THREAD

**Issue by Hareis** [mikigal/ryzen-hackintosh#44]
I recently installed 15.7 and started normally, and opened the software normally, but when I run it for a while, the mouse movement becomes very slow, the kernel_task occupancy rate in the process manager is very high, and I also tried the EFI file provided by my friend within five minutes after entering the desktop Will be stuck

**Comment by mikigal** [comment]
Sounds very weird, do you have enabled DummyPowerManagement?
Try leaving it alone for few minutes, maybe it will panic and show logs
