### ISSUE TITLE
Freeze or something when installing

### ISSUE THREAD

**Issue by tommyo4o-dev** [mikigal/ryzen-hackintosh#45]
during the installation load the apple icon again after a few times but it remains stuck at about 40%. how do i solve this?

![1BEFCA5A-2CF9-4F4C-9D16-86EBBE657686](https://user-images.githubusercontent.com/96843350/147698664-717cca96-8a36-456d-97ad-63cbcf6f407d.jpeg)

**Comment by mikigal** [comment]
Please boot with `-v debug=0x100` in boot-args and send video with logs
