### ISSUE TITLE
Ryzen 5600 B450 Kernel Panic in IONVMEController

### ISSUE THREAD

**Issue by stotes** [mikigal/ryzen-hackintosh#46]
| **Component**    | **Model**            |
| ---------------- | -------------------- |
| CPU              | 5600g           |
| Motherboard      | Gigabyte B450 I AORUS PRO WIFI​  |
| GPU              | RX 6600 XT           |
| NVME SSD | Samsung 970 EVO Plus (Latest Firmware) |

**Link to your EFI**:  [EFI.zip](https://drive.google.com/file/d/1WAk4ml0PycZ3GE6B2ZjZeRZ7qjgRm0Iv/view?usp=sharing)

![IMG_20220102_111524](https://user-images.githubusercontent.com/941055/147870638-59b9cca7-2c48-4bf1-8aa1-1a29b0371080.jpg)

**Comment by SohelIslamImran** [comment]
Hello, @stotes, I'm very new about these. What is this file? I have Ryzen 5 5600G APU-based processor, MSI B450M MORTAR MAX motherboard and 16GB ram Samsung 970 EVO Plus SSD. How can I install macOS on my PC? My purpose is to install Xcode to develop IOS app. Please give me a solution. Thank you.

**Comment by mikigal** [comment]
@stotes 
Did you find solution?

**Comment by stotes** [comment]
> @stotes Did you find solution?

I ended upgrading, so no sorry unfortunately no solution.
