### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by tiktakgames** [mikigal/ryzen-hackintosh#48]
Can i run it on
| **Component**    | **Model**            |
| ---------------- | -------------------- |
| CPU              | AMD Ryzen 5 2600           |
| Motherboard      | Gigabyte B450M S2H   |
| GPU              | Amd Radeon R9 370 Series           |
| Audio Chipset    | Something Realtek |
| Ethernet         | Realtek Gaming GBE Controller |
| WiFi & Bluetooth |   I dont have it   |

**Comment by mikigal** [comment]
Should work. You may need to apply Fake ID for GPU, more details here - https://dortania.github.io/GPU-Buyers-Guide/modern-gpus/amd-gpu.html#r7-r9

Not sure about audio and Ethernet, you didn't give correct model, but most of them are supported
