### ISSUE TITLE
Ethernet not working on Monterey

### ISSUE THREAD

**Issue by Kissadere** [mikigal/ryzen-hackintosh#49]
| **Component**    | **Model**            |
| ---------------- | -------------------- |
| CPU              | AMD RYZEN 5 2600X           |
| Motherboard      | GIGABYTE A320  |
| GPU              | AMD RX570 8GB          |
| Audio Chipset    | APPLEALC |
| Ethernet         | REALTEK |
| WiFi & Bluetooth | NONE |

**Link to your EFI**: https://disk.yandex.com/d/BDHndi4j5ntoew

I can't get the Ethernet (en0) to work on MacOS Monterey. I've tried everything from https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html#fixing-en0 and also tried every single version of RealtekRTL811 Kext. No one them works.
Note: Ethernet works on any other version (Mojave and Catalina) but won't work with Monterey.

**Comment by mikigal** [comment]
Which Realtek chip do you have? Are you sure that it's 8111?

**Comment by Kissadere** [comment]
At this point i'm not 100% sure which one i'm using. 

Although, i've been using that specific kext since Mojave and never had an issue, until now with Monterey. Everything else works fine, it's just the Ethernet that doesn't work.

**Comment by mikigal** [comment]
Show output of `kextstat | grep -v com.apple`

**Comment by Kissadere** [comment]
Here's a screenshot of my output: https://imgur.com/MtADVbj

(I'm right now using Big Sur, since Monterey won't work)

**Comment by mikigal** [comment]
Check if RTL8111 kext is loaded on Monterey too

**Comment by Kissadere** [comment]
I have no access to Monterey as this is my only PC with Mac, i'll have to update and i don't think i'll be able to access Github after that xD

**Comment by mikigal** [comment]
Simply install Monterey on second partition and use pendrive for your EFI

**Comment by Hesowcharov** [comment]
@mikigal Hi! First of all, thank you so much for such great project. With your work I was able to boot Big Sur on my PC (B450m DS3H: RX570 + Ryzen 2600). It's amazing and incredible!

But now I'm experiencing the same issue on Monterey. Before taking the OTA with Monterey, I pulled your last changes from the repo and ensured that it still works on Big Sur. Then I installed the update and came up to the bootable state of OS and everything seems working except the wired ethernet connection.  In my case, the network settings shows me 'Cable Unplugged'. I've tried to configure the hardware settings in there manually (as someone recommends in the [thread](https://www.insanelymac.com/forum/topic/287161-new-driver-for-realtek-rtl8111/page/64/)) but it didn't help.
How did you switch to Monterey ? Did you update via OTA or get it from the clean install ? Maybe I need to do something else after updating (clean and rebuild kext caches, idk) ?
Thanks in advance!

**Comment by mikigal** [comment]
I don't remember how I switched to Monterey, but even if it's OTA update nothing more is required (e. g. rebuilding caches). I didn't have issue like this with Ethernet, also I no longer have hackintosh so I can't help so much.
You may ask on AMD-OSX Discord for help. If you get solution please let me know or make pull request, I will add it to README

**Comment by caelou318** [comment]
> **Component**	**Model**
> CPU	AMD RYZEN 5 2600X
> Motherboard	GIGABYTE A320
> GPU	AMD RX570 8GB
> Audio Chipset	APPLEALC
> Ethernet	REALTEK
> WiFi & Bluetooth	NONE
> **Link to your EFI**: https://disk.yandex.com/d/BDHndi4j5ntoew
> 
> I can't get the Ethernet (en0) to work on MacOS Monterey. I've tried everything from https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html#fixing-en0 and also tried every single version of RealtekRTL811 Kext. No one them works. Note: Ethernet works on any other version (Mojave and Catalina) but won't work with Monterey.

I'm not sure what version of ethernet controller you have. I did find this one work for me ([I225-V](https://github.com/dortania/bugtracker/issues/213#)).
Have you tried inserting boot-arg `dk.e1000=0`? You can also tried patching it.

**Comment by mikigal** [comment]
I no longer have hackintosh, also I always had Realtek ethernet chipsets so I can't do anything. When someone else find solution. I will update README

**Comment by Hesowcharov** [comment]
someone who is looking for alternative solution - you can try to use a wifi usb-adapter with drivers from https://github.com/chris1111/Wireless-USB-OC-Big-Sur-Adapter

**Comment by wolter8** [comment]
> someone who is looking for alternative solution - you can try to use a wifi usb-adapter with drivers from https://github.com/chris1111/Wireless-USB-OC-Big-Sur-Adapter

I have same problem, with MSI X570-A Pro and ethernet 8111 is not working. I've tried several kexts version with no luck.

**Comment by mikigal** [comment]
@wolter8 
`Supports Realtek RTL8111/8168 B/C/D/E/F/G/H found on recent boards.`
MSI X570-A Pro has RTL8111H so in theory it's supported (Specs: https://www.msi.com/Motherboard/X570-A-PRO/Specification).

You can create issue in kext's repository: https://github.com/Mieze/RTL8111_driver_for_OS_X
Then you have to find logs of this kext's in boot log (you have to boot into verbose mode) to help finding the issue

**Comment by Kissadere** [comment]
Try this other version instead, this one worked for me: https://github.com/Mieze/RTL8111_driver_for_OS_X/files/8414872/RealtekRTL8111.zip 06.03.2023, 16:11, "Mikołaj Gałązka" ***@***.***>***@***.*** @caelou318 @Kissadere @HesowcharovDid anyone find fix for this issue?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>  -- Tarkkaavaisesti, Christopher CossPerustaja, Zibuu ***@***.*** ***@***.***

**Comment by caelou318** [comment]
> @wolter8 @caelou318 @Kissadere @Hesowcharov
> Did anyone find fix for this issue?

Hi there, try using Kernel Patch with boot-args e1000=0. I've only tested this on macOS 12.3+ Monterey

**Comment by mikigal** [comment]
Thanks, I added this information to README
