### ISSUE TITLE
I have a problem, which is beyond my ability, can you give me some ideas?

### ISSUE THREAD

**Issue by DemoorBug** [mikigal/ryzen-hackintosh#52]
System: Big Sur 16.1
CPU: AMD 3600
Language: Python

<img width="531" alt="截屏2022-11-03 下午3 51 50" src="https://user-images.githubusercontent.com/18387615/199670271-aecb1a4e-4269-4533-a1a4-b0db4839d6fd.png">
When I use matplotlib, it reports Intel MKL ERROR. CPU 0 is not supported.

I applied the ryzen_patch patch, but it didn't work.

**Comment by mikigal** [comment]
You have to create library to "fake" intel MKL.
Read this: https://gist.github.com/bebosudo/6f43dc6b4329c197f258f25cc69f0ec0
You can also append LD_PRELOAD variable on boot using LauncherAgent/LauncherDaemon

**Comment by DemoorBug** [comment]
I also tried this method, it did not work.
His solution is to increase the speed, my problem is that it does not work and reports an error.

**Comment by mikigal** [comment]
It does not only increase speed, I used it for Adobe software some time ago when I had same issue as you.
Try to do this from terminal:
`LD_PRELOAD=patj/to/fake.so python3 myscript.py`

**Comment by DemoorBug** [comment]
fakeintel.c
```c
int mkl_serv_intel_cpu_true() {
 return 1;
}
```
```bash
touch libfakeintel.so
gcc -shared -fPIC -o libfakeintel.so fakeintel.c
LD_PRELOAD=libfakeintel.so python3 scratch.py
```
<img width="898" alt="2022-11-03 4 49 31" src="https://user-images.githubusercontent.com/18387615/199679592-75a87019-506e-460b-979d-84edc2429760.png">

**Comment by mikigal** [comment]
Try compiling it to dylib: `gcc -dynamiclib /Users/tomnic/Desktop/fakeintel.c -o libfakeintel.dylib`
Source (and author of this lib idea): https://www.macos86.it/topic/4822-wip-photoshop-after-effects-cc-2021-premiere-pro-cc-2021-154-amd-hackintosh-fix/

**Comment by DemoorBug** [comment]
<img width="957" alt="2022-11-03 5 02 01" src="https://user-images.githubusercontent.com/18387615/199681840-f4be4109-32a1-4271-af5b-961c78fc307f.png">

**Comment by DemoorBug** [comment]
Can your Black Apple run this code?
```python
import matplotlib.pyplot as plt
  xt, yt=1,2
  plt.plot(xt,yt,'ro')
  plt.show()
```

**Comment by DemoorBug** [comment]
https://gist.github.com/bebosudo/6f43dc6b4329c197f258f25cc69f0ec0 The code in this example also reports the same error

**Comment by mikigal** [comment]
I no longer use hackintosh, so I can't verify your problem.
You can try asking on AMD-OSX Discord

**Comment by DemoorBug** [comment]
Well, but thank you anyway

**Comment by DemoorBug** [comment]
I was using matplotlib provided by anaconda, and it turned out to be the problem, I just uninstalled it.
I installed it via `python3 -m pip install -U matplotlib` and it didn't report any errors. I'm so stupid, I wasted your time.🥲
