### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by Bhavin-kareliya** [mikigal/ryzen-hackintosh#53]
| **Component**    | **Model**            |
| ---------------- | -------------------- |
| CPU              | AMD Ryzen 9  3900x 12 Core           |
| Motherboard      | ASUS B550 Prime WiFi   |
| GPU              |  AMD Radeon RX 570 8 GB           |
| WiFi & Bluetooth |  Fenvi T919 (BCM94360CD)    |

EFI Link
https://drive.google.com/file/d/1cc6AnQlCPYtXgZsrds-mMlAlWgmiTPyq/view

![WhatsApp Image 2022-11-03 at 18 35 29](https://user-images.githubusercontent.com/54073491/199732141-157b1b9a-ce2f-4f02-976c-06ac7e35a1c0.jpg)

![WhatsApp Image 2022-11-03 at 18 35 291](https://user-images.githubusercontent.com/54073491/199732194-e5aec837-b0bb-41b7-800e-ca3300b3330a.jpg)

I have followed your setup, I am stuck at Startup.
Can you please help me to resolve the issue?
Thanks!

**Comment by jekingohel** [comment]
I have same hardware configuration and getting same issue.
Can anyone know how to fix startup issue?

**Comment by mikigal** [comment]
Do you boot into verbose boot or normally?

**Comment by jekingohel** [comment]
@mikigal 
I have removed USBToolBox and UTBMap kexts, but still I got the same error.

**Comment by jekingohel** [comment]
@mikigal 
Everything working well except

- Airdrop is not fully working. Can receive files from airdrop but could not send.
- Handoff is not working
- Universal controller is not working.
- Sidecar is not working

Can you please help me to resolve above issue?

**Comment by jekingohel** [comment]
<img width="972" alt="image" src="https://user-images.githubusercontent.com/2361463/200326408-19b24fe6-60ec-4163-aff3-fe9b340c3bf3.png">

Above is my platform information

**Comment by mikigal** [comment]
@jekingohel How did you fixed booting issue?
Fenvi should workd OOTB (at least it worked in Monterey, when I had last hackintosh)

Sidecar is unfixable/very hard to fix with AMD, not sure how about Universal Control, I didn't use it. Check this: https://github.com/acidanthera/FeatureUnlock

**Comment by mikigal** [comment]
Sidecar will not be supported in this repository as I can not test it, additionally it's very hardware dependent feature
