### ISSUE TITLE
I have 2 questions here, hope you can help me out~

### ISSUE THREAD

**Issue by hevinzhou** [mikigal/ryzen-hackintosh#54]
| **Component**    | **Model**            |
| ---------------- | -------------------- |
| CPU              | ryzen 2600   |
| Motherboard      | ASUS B350 Plus  |
| GPU              |   Dataland RX580  8G X-Serial      |
| Audio Chipset    | [ignore that] |
| Ethernet         | Realtek RTL8111 |
| WiFi & Bluetooth |   Fenvi T919 (BCM94360CD)  |

I hope you can help me with these two questions:

questions1:
I'm installed monterey 12.2.1 OS .But when I try to update 13.0 OS raise [EB|#LOG:EXITBS:START] error.There's someboby say should I close the CFG LOCK settings whit my montherboard.I'm use Montherboard which is ASUS B350 Plus.same as your. How to close the CFG LOCK?

questions2: 
on monterey 12.2.1 OS is work.But my mouse always in loading status at the desktop, sometimes I set cpu to 3040Mhz at AMDRyzenCPUPowerManagement.app maybe can fixed it utill I reboot my mac.Can I fix the loading problem by opencore settings?

**Comment by mikigal** [comment]
Hi, did you modify kernel patches for your CPU? If not, that's reason of booting issue. Also make sure you got latest version from my repository, I updated everything for Monterey support few weeks ago.

What do you mean by "loading status"? Try removing AMDRyzenCPUPowerManagement and SMCAMDProcessor kexts and run some Geekbench. Then verify is score similar to other on same configuration as your

**Comment by hevinzhou** [comment]
thank you ! I update to latest version now.
