### ISSUE TITLE
Restarting Loop (with error) macOS

### ISSUE THREAD

**Issue by PeacefulTrees** [mikigal/ryzen-hackintosh#55]
Hello, i have a problem with the OpenCore bootloader :/
| **Component**    | **Model**            |
| ---------------- | -------------------- |
| CPU              | Ryzen 7 5700G (graphics adapter disable)           |
| Motherboard      | MSi B450 Tomahawk MAX |
| GPU              | Nvidia PASCAL (gtx 1050 2gb)           |
| Audio Chipset    | Realtek® ALC892 Codec (i use usb audio adapter) |
| Ethernet         | Realtek® 8111H Gigabit LAN  |
| WiFi & Bluetooth | I don't have it and dont need this    |
| ---------------- | -------------------- |
Wanted macOS: High Sierra 10.13.6
| ---------------- | -------------------- |
**EFI**: 
http://de1.oelerat.fr:25611/file/EFI.zip (is my personnal server)
| ---------------- | -------------------- |

I have succefully installed my wanted macOS versions with the recovery mode.
When i loading the OpenCore (i have OCB LoadImage failed - Unsupported...)
When i choose my macOS Disks: 
End SetConsoleMode
Start OpenKernelRootVolume
End OpenKernelRootVolume
OC: Prelinked injection SMCAMDProcessor.kext  ()  - invalid parameters

And after, my computer go to reboot in loooop
Can you help me?
Cordially
Ezermoz

**Comment by mikigal** [comment]
@Ezermoz 
Hi, what version of macOS are you trying to install?

**Comment by mikigal** [comment]
@Ezermoz 
Hi, I guess SMCAMDProcessor does not support macOS High Sierra, it's very old version.
Remove SMCAMDProcessor and AMDRyzenCPUPowerManagement kexts. Remember to remove them from config too

**Comment by Ezermoz** [comment]
I have deleted the specific kext and modify into the plist files, i have always the same error, i have reinstall macos with the recovery... 
When i loading the OpenCore (i have OCB LoadImage failed - Unsupported...)
when i want to boot on the disk:
End SetConsoleMode
Start OpenKernelRootVolume
End OpenKernelRootVolume

(this time i dont have smcsproccess invalid....)
And he reboot again to opencore (boot loop)
