### ISSUE TITLE
Support for HP all-in-one with Ryzen 4500U

### ISSUE THREAD

**Issue by nospam2k** [mikigal/ryzen-hackintosh#58]
Should this work with HP all-in-one with Ryzen 4500U? It's called HP all-in-one 24

**Comment by mikigal** [comment]
I guess it will not work on AIO systems same as on laptops, but you have to verify it

**Comment by nospam2k** [comment]
I'm not sure how I can verify this if I'm not sure how to even install it! For example? What GPU should I use?

**Comment by mikigal** [comment]
Hi,
here's official guide about hardware compatibility: https://dortania.github.io/Anti-Hackintosh-Buyers-Guide/

All-In-One system may have additional issues, like problems with BIOS/ACPI, touchscreen (if you have it) and integrated GPU
