### ISSUE TITLE
it stuck on apple logo 

### ISSUE THREAD

**Issue by UsetUset2244** [mikigal/ryzen-hackintosh#61]
it is s loading  for me taking hours  and still not complete

**Comment by mikigal** [comment]
Please boot in verbose mode and check where it stuck

**Comment by UsetUset2244** [comment]
how to do this

**Comment by UsetUset2244** [comment]
i managed to do this and this is what im getting @mikigal

**Comment by mikigal** [comment]
Looks like ACPI issue. Please post your computer's specs

**Comment by mikigal** [comment]
RTX 3060 won't work on ANY version of macOS

**Comment by UsetUset2244** [comment]
it worked alrealy had to add something in boot args thanks for closing the issue forget to do that

**Comment by plumsydev** [comment]
Hi!
Did you manage to fix that?
Having an B550 board with all patches needed in the readme, with an r5 5500 and an RX 6500 XT
I'm stuck on this too (Monterey)
Haven't tried Ventura / Sonoma yet
