### ISSUE TITLE
Internet connection is required

### ISSUE THREAD

**Issue by Entretoize** [mikigal/ryzen-hackintosh#62]
CPU Ryzen 7 2700
X570 Phantom Gamin 4
NVIDIA GeFor RTX 3080
Intel I211 Gigabit Ehternet
Realtek 8821CU Wireless

I can boot the mac install but when I try to start the macos installation, it says an internet connection is required.
My ethernet card is an Intel I211 Gigabit and I'm installing Ventura.
I installed many kext trying (AppleIGB.kext, LucyRTL8125Ethernet.kext, SmallTreeIntel82576.kext...) and added "e1000=0" to boot args but that doesn't work, what can I do ?

**Comment by mikigal** [comment]
I never worked with Intel ethernet card so I can't help so much.
Please ask on AMD-OSX Discord and let me know if you find something - I will add it to README.
For now I don't have any hackintosh machine for testing

**Comment by Entretoize** [comment]
The right one was SmallTreeIntel82576.kext, I just didn't know I add to write something in the config.plist:

```
	<key>Kernel</key>
	<dict>
		<key>Add</key>
		<array>
                                        ...
			<dict>
				<key>Arch</key>
				<string>x86_64</string>
				<key>BundlePath</key>
				<string>SmallTreeIntel82576.kext</string>
				<key>Comment</key>
				<string></string>
				<key>Enabled</key>
				<true/>
				<key>ExecutablePath</key>
				<string>Contents/MacOS/SmallTreeIntel82576</string>
				<key>MaxKernel</key>
				<string></string>
				<key>MinKernel</key>
				<string></string>
				<key>PlistPath</key>
				<string>Contents/Info.plist</string>
			</dict>
                                ...
```
