### ISSUE TITLE
Support for Ryzen 7 4800H

### ISSUE THREAD

**Issue by HackerShohag** [mikigal/ryzen-hackintosh#63]
| **Component**    | **Model**            |
| ---------------- | -------------------- |
| CPU              | AMD Ryzen 7 4800H with Radeon Graphics           |
| Motherboard      | ASUSTeK COMPUTER INC. FA506ICB   |
| GPU              | NVIDIA GeForce RTX™ 3050 Laptop GPU / AMD Radeon™ Graphics           |
| Audio Chipset    | Advanced Micro Devices, Inc. [AMD/ATI] Renoir Radeon High Definition Audio Controller |
| Ethernet         | Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 15) |
| WiFi & Bluetooth | MT7921 802.11ax PCI Express Wireless Network Adapter     |

I want to know that if my laptop will support this EFI for booting macOS ventura. If not plese, help me on going.

My Laptop info is [here](https://www.startech.com.bd/asus-tuf-gaming-a15-fa506icb-ryzen-7-4800h-laptop).

**Comment by mikigal** [comment]
Your Nvidia GPU is not supported.
In general AMD laptops are not supported, you may have a lot of issues, e. g. with ACPI and power management and you will have to handle it yourself.

There's kext for integrated graphics in Ryzen but it's in development state and may not work correctly - https://github.com/NootInc/NootedRed

You can try booting macOS on your laptop but definetly you have to make EFI on your own, as this one does not support mobile devices
