### ISSUE TITLE
Cannot boot into Monterey, reboots  -X86PlatformPlugin

### ISSUE THREAD

**Issue by xavierbaez** [mikigal/ryzen-hackintosh#64]
| **Component**    | **Model**            |
| ---------------- | -------------------- |
| CPU              | AMD Ryzen 9 590 16 Core         |
| Motherboard      | Asus ROG X570 Crosshair VIII Formula AM4  |
| GPU              Radeon RX 580 8 GB           |
| Audio Chipset    | USB |
| Ethernet         | Intel |
| WiFi & Bluetooth | Intel     |

I cannot boot into Monterey

Error I get:
```
X86PlatformPlugin::cgConfigResourceHandler — delay registering service until num proccessors is 0: -1 and SMC handler is valid
``` 

1. Big Sur
2. Ventura
But it will not boot into Monterey

After 5-10 minutes, it reboots

**Comment by xavierbaez** [comment]
![B7AEDC90-8810-49E3-887C-42C0828E0E7E](https://github.com/mikigal/ryzen-hackintosh/assets/1647474/a1310bab-01b8-4cce-8a56-3dd5b5809c53)

**Comment by SNnT23** [comment]
I want use  this. 
My Specs 
Ryzen 5 5600 non x
MSI GAMING X 3060 TI 8GB
Memory 16GB
Please Gudie me, Sir.

**Comment by mikigal** [comment]
Hi,
NVIDIA GPUs are not supported in systems newer than macOS High Sierra (10.13).
Even if issue is not GPU related there's no sense to fix it as system will be unusable without supported GPU

**Comment by xavierbaez** [comment]
This should be reopened please
I have AMD GPU
Here is the kernel panic:
`panic(cpu 18 caller 0xffffff802197999f): userspace watchdog timeout: no successful checkins from logd in 120 seconds
service returned not alive with context : unresponsive dispatch queue(s): com.apple.firehose.io-wl 
service: logd, total successful checkins since load (270 seconds ago): 16, last successful checkin: 120 seconds ago
service: opendirectoryd, total successful checkins since load (270 seconds ago): 27, last successful checkin: 0 seconds ago

Panicked task 0xffffff953a0793b0: 5 threads: pid 130: watchdogd
Backtrace (CPU 18), panicked thread: 0xffffff86d859a540, Frame : Return Address
0xfffffff52c143690 : 0xffffff801e47fd6d mach_kernel : _handle_debugger_trap + 0x41d
0xfffffff52c1436e0 : 0xffffff801e5e1086 mach_kernel : _kdp_i386_trap + 0x116
0xfffffff52c143720 : 0xffffff801e5d03f3 mach_kernel : _kernel_trap + 0x4d3
0xfffffff52c143770 : 0xffffff801e41fa70 mach_kernel : _return_from_trap + 0xe0
0xfffffff52c143790 : 0xffffff801e48013d mach_kernel : _DebuggerTrapWithState + 0xad
0xfffffff52c1438b0 : 0xffffff801e47f8f6 mach_kernel : _panic_trap_to_debugger + 0x2b6
0xfffffff52c143910 : 0xffffff801ed14ec3 mach_kernel : _panic_with_options + 0x89
0xfffffff52c143a00 : 0xffffff802197999f com.apple.driver.watchdog : __ZN10IOWatchdog14userspacePanicEP8OSObjectPvP25IOExternalMethodArguments.cold.1 + 0x27
0xfffffff52c143a10 : 0xffffff80219795f2 com.apple.driver.watchdog : __ZN10IOWatchdog35userspaceDisableUserspaceMonitoringEP8OSObjectPvP25IOExternalMethodArguments
0xfffffff52c143a30 : 0xffffff8021978971 com.apple.driver.watchdog : __ZN20IOWatchdogUserClient14externalMethodEjP25IOExternalMethodArgumentsP24IOExternalMethodDispatchP8OSObjectPv + 0x7f
0xfffffff52c143b60 : 0xffffff801ec8365c mach_kernel : _is_io_connect_method + 0x42c
0xfffffff52c143cc0 : 0xffffff801e586d86 mach_kernel : _iokit_server_routine + 0x4f56
0xfffffff52c143dd0 : 0xffffff801e45a9ab mach_kernel : _ipc_kmsg_send + 0x46b
0xfffffff52c143e60 : 0xffffff801e4711a9 mach_kernel : _mach_msg_overwrite_trap + 0x2c9
0xfffffff52c143ef0 : 0xffffff801e5b305a mach_kernel : _mach_call_munger64 + 0x1ea
0xfffffff52c143fa0 : 0xffffff801e420256 mach_kernel : _hndl_mach_scall64 + 0x16
      Kernel Extensions in backtrace:
         com.apple.driver.watchdog(1.0)[8BE4EE7F-9150-3161-BE84-36874BF82DE2]@0xffffff8021977000->0xffffff8021979fff

Process name corresponding to current thread (0xffffff86d859a540): watchdogd
Boot args: npci=0x2000 unfairgva=1 alcid=11 -v debug=0x100 keepsyms=1 chunklist-security-epoch=0 -chunklist-no-rev2-dev

Mac OS version:
21G83

Kernel version:
Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64
Kernel UUID: D0DC2052-71F4-3DCB-B189-BEE5A59B3B42
KernelCache slide: 0x000000001e200000
KernelCache base:  0xffffff801e400000
Kernel slide:      0x000000001e210000
Kernel text base:  0xffffff801e410000
__HIB  text base: 0xffffff801e300000
System model name: MacPro7,1 (Mac-27AD2F918AE68F61)
System shutdown begun: NO
Panic diags file available: NO (0xe00002bc)
Hibernation exit count: 0

System uptime in nanoseconds: 273666239387
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x0000003fb8f9f886
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x0000001819873886 0x0000000000000000
Compressor Info: 0% of compressed pages limit (OK) and 0% of segments limit (OK) with 0 swapfiles and OK swap space
Zone info:
  Zone map: 0xffffff806b210000 - 0xffffffa06b210000
  . PGZ   : 0xffffff806b210000 - 0xffffff8073211000
  . VM    : 0xffffff8073211000 - 0xffffff853ebaa000
  . RO    : 0xffffff853ebaa000 - 0xffffff86d7edd000
  . GEN0  : 0xffffff86d7edd000 - 0xffffff8ba3876000
  . GEN1  : 0xffffff8ba3876000 - 0xffffff906f20f000
  . GEN2  : 0xffffff906f20f000 - 0xffffff953aba8000
  . GEN3  : 0xffffff953aba8000 - 0xffffff9a06542000
  . DATA  : 0xffffff9a06542000 - 0xffffffa06b210000
  Metadata: 0xffffffc06b660000 - 0xffffffc08b660000
  Bitmaps : 0xffffffc08b660000 - 0xffffffc0a3660000`
