### ISSUE TITLE
Using NootedRed to cover AMD iGPUs

### ISSUE THREAD

**Issue by Otus9051** [mikigal/ryzen-hackintosh#67]
I saw the lack of iGPU support in this repo, I would like to suggest the usage of NootedRed (https://chefkissinc.github.io/nred) for the same. I have already used it in my EFI (https://github.com/Otus9051/Hackintosh-HP-15s-eq2144au).

Is there any other particular reason this is not included?

**Comment by mikigal** [comment]
The only reason is that I can not test it (I'm using Intel setup with Windows now) so I can't provide any guide about it

**Comment by Otus9051** [comment]
It's supposed to be a drop-in replacement for WhateverGreen. 
Recommended to have >1024MB of VRAM or else Electron apps crash (its a macOS thing).
Use Smokeless-UMAF for that, if you don't have an unlocked BIOS.
Closing issue as resolved.
