### ISSUE TITLE
USB lost power randomly

### ISSUE THREAD

**Issue by jiatao99** [mikigal/ryzen-hackintosh#68]
### macOS Version

Ventura (13.x)

### Specification

| **Component**    | **Model**            |
| ---------------- | -------------------- |
| CPU              | AMD 3900x           |
| Motherboard      | Asus B550M Plus Wifi   |
| GPU             | Gigabyte RX6600       |

### What happened?

Hi guys,

Thank you SOOO much to rescue my newly bought RX6600. I tried multiple guide to install Ventura/Monterey but always got black screen or auto reboot after verbose. Until I found your wonderful EFI and modify on top of it, I can finally install and use my RX6600.

I got GPU, sound, ethernet working. However, I still have one problem:

1. Most annoying thing: my usb keyboard randomly lost power (Caps Lock not lighting up). I have to keep changing my USB port. Windows (dual boot) works just fine.
2. I have Parallel Desktop 13. But how to install it?

How to fix this issue? 

Thanks for your great works

Tao

Some observation:

1. Install Ventura on top of BigSur always got boot loop
3. Must first install the Monterrey. However at the end, I got apple panic
4. Install Ventura now, it will say firmware upgrade is required at the end. At this point, the Monterrey is bootable. Haha
5. Install Ventura again with -v debug=0x100 removed (must), I can do a second install and I am able to log into Ventura

### Your EFI link

Will upload if required

### Before creating an issue

- [X] I tried fixing this issue myself and asked for support on [AMD-OSX Discord](https://discord.gg/EfCYAJW)
- [X] I filled my computer specification
- [X] I attached logs with enabled verbose mode

**Comment by mikigal** [comment]
Hi,
please verify is your USB mapped correctly. Also you can switch `USB Legacy Support/OPROM` in BIOS settings.
As last chance you can try removing your USB map and USBToolBox kext

**Comment by mikigal** [comment]
No reponse
