### ISSUE TITLE
Remove serial number stuff

### ISSUE THREAD

**Issue by reimertz** [mikigal/ryzen-hackintosh#7]
Hey there! 

This is just a friendly tip that you probably should remove these serial number stuff. 
You never know if Apple snopes around here or bad some bad actors. 

<3

https://github.com/mikigal/ryzen-hackintosh/blob/798076f4d9cc887a1aa5b115d9da2d5ac8c4f4e9/OC/config.plist#L1348

**Comment by mikigal** [comment]
Hi,
this SMBIOS informations were generated for this repository, not my private. When I remove it, if user forget to put these informations OpenCore will show errors, and won't boot. I think it's easier for testing for users with sample SMBIOS informations

**Comment by reimertz** [comment]
Fair point. Wonder if there is a middle ground because if to many use the same serial numbers, I would be worried their Apple IDs might get blacklisted. :S
