### ISSUE TITLE
My Installation Experience

### ISSUE THREAD

**Issue by Kotaless** [mikigal/ryzen-hackintosh#70]
Hi mikigal, 
I was able to install Sonoma -thanks to your great guide- and I'd like to share my experience for you to update your readme!
My system: B450, Ryzen 5500, RX 6600

- You don't need to disable "Resizable BAR Support" if `ResizeAppleGpuBars=0` set.
https://dortania.github.io/OpenCore-Install-Guide/AMD/zen.html#quirks-2
- I had to set `SecureBootModel=Disabled` in order to successfully complete the installation. Currently using `SecureBootModel=j160` but I don't know if it will cause any issues while installing.
This page could be mentioned: https://dortania.github.io/OpenCore-Post-Install/universal/security/applesecureboot.html#securebootmodel
- You mention `agdpmod=pikera` for Navi 10 but I believe it's also valid for Navi 20. I got black screen without it.
https://dortania.github.io/GPU-Buyers-Guide/misc/bootflag.html#amd-boot-arguments
- Microphone input (3.5mm Jack) works pretty well after AppleALC 1.8.8.
https://github.com/acidanthera/AppleALC/releases/tag/1.8.8

![Screenshot 2024-04-12 at 3 19 54 PM](https://github.com/mikigal/ryzen-hackintosh/assets/9118532/cdc4a8e1-d943-4566-bf14-768cc97310b3)

**Comment by mikigal** [comment]
Hi,
thank you for the feedback!
I've updated the README with your suggestions - https://github.com/mikigal/ryzen-hackintosh/commit/69f2a3745b738479353c883c66d144a2b014e9ff

**Comment by talhazahid** [comment]
Hey @Kotaless can you share your EFI file?

**Comment by Kotaless** [comment]
> Hey @Kotaless can you share your EFI file?
I don't think it's a good idea but here it is. Don't forget to update SMBIOS (I'm using MacPro7,1).
https://github.com/mikigal/ryzen-hackintosh?tab=readme-ov-file#smbios
[EFI.zip](https://github.com/user-attachments/files/16201549/EFI.zip)

**Comment by talhazahid** [comment]
> > Hey @Kotaless can you share your EFI file?
> 
> I don't think it's a good idea but here it is. Don't forget to update SMBIOS (I'm using MacPro7,1) and map your USB ports. https://github.com/mikigal/ryzen-hackintosh?tab=readme-ov-file#smbios [EFI.zip](https://github.com/user-attachments/files/16201549/EFI.zip)

Thanks.. I got my working without using your EFI.. I dont know how maybe clearing NVRAM twice did the trick and also by disabling secure boot from Config
