### ISSUE TITLE
Question: Parallels 13.1 install on Ventura

### ISSUE THREAD

**Issue by flyingk** [mikigal/ryzen-hackintosh#72]
### macOS Version

Ventura (13.x)

### Specification

Ryzen 9, AM5 platform, OC 0.9.9

### What happened?

Hi, Just wondering if there are any tricks getting Parallels 13.1 installed (apart from the env. variable) or is it just too old? SVM in Bios is enabled. I assume your launcher app only works with an installed version?

Thanks a lot.

### Your EFI link

none

### Before creating an issue

- [X] I tried fixing this issue myself and asked for support on [AMD-OSX Discord](https://discord.gg/EfCYAJW)
- [X] I filled my computer specification
- [X] I attached logs with enabled verbose mode

**Comment by flyingk** [comment]
Thanks for the detailed writeup in the readme. Very helpful information :)

**Comment by mikigal** [comment]
In Big Sur (11.0) adding env variable `SYSTEM_VERSION_COMPAT=1` to installer and app fixed problem, but I'm not sure does it still work for newer versions
