### ISSUE TITLE
icloud can't login

### ISSUE THREAD

**Issue by kingdo-man** [mikigal/ryzen-hackintosh#8]
bro,i updated my hackintosh to 11.0 beta5 from 10.15.6 ,and i exited my apple id,then i can't login again.
system point out Unable to contact the server
my specification：
2700 msi b350m 5700xt fenvi t919 sumsung 960pro

**Comment by kingdo-man** [comment]
please help me

**Comment by htanh034** [comment]
> please help me

Same for me.

1. Try change flatform info
2. New install Macosx connect icloud while setup ( fixed ).

B450 R5 3600.

**Comment by mikigal** [comment]
Looks like macOS issue.
Try this: https://osxdaily.com/2016/10/23/fix-icloud-unknown-error-cant-connect-problem-mac/
Also make sure your NIC is en0
