### ISSUE TITLE
No receive audio for main MSI B350M Motar

### ISSUE THREAD

**Issue by phucdth12a** [mikigal/ryzen-hackintosh#9]
I use this resource and setup success but it not receive audio. 

i use main MS B350M motar, ryzen 5 1600

**Comment by mikigal** [comment]
Your motherboard have ALC892 audio chipset. You have to find layout id, which work for you. Try IDs from table, put it in alcid=x boot parameter 

https://github.com/acidanthera/applealc/wiki/supported-codecs
